config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  unauthenticated do
    root to: 'home#index', as: :unauthenticated_root
  end

  authenticated :user do
    constraints ->(req) { req.env['warden'].user.role == 'admin' } do
      root to: 'system/dashboard#index', as: :admin_root
    end

    root to: 'main/posts#index'
  end

  namespace :system do
    resources :users
    resources :posts do
      member do
        put 'post_published'
        put 'cancel'
      end
    end
  end

  namespace :main do
    resources :users, except: %i[index create new]
    resources :posts do
      member do
        put 'post_published'
        put 'cancel'
      end
    end
  end

  devise_for :users, path: 'auth', controllers: {
    registrations: 'auth/registrations',
    omniauth_callbacks: 'auth/omniauth_callbacks'
  }
end

app/models/user.rb
# frozen_string_literal: true

require 'open-uri'

class User < ApplicationRecord
  extend Enumerize

  has_many :posts

  has_one_attached :avatar do |attachable|
    attachable.variant :thumb, resize_to_limit: [300, 300]
    attachable.variant :min, resize_to_limit: [200, 200]
  end

  validates :first_name,
            :last_name,
            :nickname,
            :role,
            presence: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :trackable, :timeoutable, :confirmable,
         :omniauthable, omniauth_providers: %i[google_oauth2 github]

  enumerize :role,
            in: %i[user admin],
            default: :user,
            predicates: true,
            scope: true

  scope :with_admin_role, -> { where(role: :admin) }
  scope :with_user_role, -> { where(role: :user) }

  def self.ransackable_attributes(_auth_object = nil)
    %w[email first_name id last_name nickname phone_number role]
  end

  def self.ransackable_associations(_auth_object = nil)
    []
  end

  def full_name
    "#{first_name} #{last_name}".titleize
  end

  def display_name
    return email if full_name.blank?

    full_name
  end
end

app/controllers/main/users_controller.rb
# frozen_string_literal: true

module Main
  class UsersController < Main::ApplicationController
    before_action :set_user, only: %i[show edit update destroy]

    def show
      @user = User.find(params[:id])
      @post = Post.where(user_id: @user)
    end

    def edit
      authorize @user, :edit?
    end

    def update
      authorize @user, :update?

      respond_to do |format|
        if @user.update(user_params)
          format.html { redirect_to main_user_path(@user), notice: 'Your profile was successfully updated.' }
          format.json { render :show, status: :ok, location: @user }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      authorize @user, :destroy?

      @user.destroy
      respond_to do |format|
        format.html { redirect_to unauthenticated_root_path, notice: 'User was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private

    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(policy(User).permitted_attributes)
    end
  end
end

app/controllers/system/application_controller.rb
# frozen_string_literal: true

module System
  class ApplicationController < ::ApplicationController
    before_action :authenticate_user!
    before_action :redirect_user

    layout 'system'

    private

    def redirect_user
      return unless user_signed_in? && !current_user.admin? && !devise_controller?

      flash[:error] = 'You do not have permission to go to administrative pages!'

      redirect_to main_posts_path
    end
  end
end

app/controllers/system/dashboard_controller.rb
# frozen_string_literal: true

module System
  class DashboardController < System::ApplicationController
    def index; end
  end
end

app/controllers/system/posts_controller.rb
# frozen_string_literal: true

module System
  class PostsController < System::ApplicationController
    before_action :set_post, only: %i[show edit update destroy]

    def index
      @q = Post.ransack(params[:q])
      @posts = @q.result(distinct: true)
      @pagy, @posts = pagy(@q.result)
    end

    def show; end

    def new
      @post = current_user.posts.build
    end

    def edit; end

    def create
      @post = current_user.posts.build(post_params)

      respond_to do |format|
        if @post.save
          format.html { redirect_to system_post_url(@post), notice: 'Post was successfully created.' }
          format.json { render :show, status: :created, location: @post }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end

    def update
      respond_to do |format|
        if @post.update(post_params)
          format.html { redirect_to system_post_url(@post), notice: 'Post was successfully updated.' }
          format.json { render :show, status: :ok, location: @post }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      @post.destroy!

      respond_to do |format|
        format.html { redirect_to system_posts_url, notice: 'Post was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    def post_published
      @post = Post.find(params[:id])

      @post.make_published!
      flash[:success] = "Post #{@post.id} has been published."
      redirect_to system_post_path(@post)
    end

    def cancel
      @post = Post.find(params[:id])

      @post.cancel!
      flash[:success] = "Post #{@post.id} has been cancelled."
      redirect_to system_post_path(@post)
    end

    private

    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(policy(Post).permitted_attributes)
    end
  end
end

app/controllers/system/users_controller.rb
# frozen_string_literal: true

module System
  class UsersController < ApplicationController
    before_action :set_user, only: %i[show edit update destroy]

    def index
      authorize User, :index?

      @q = User.ransack(params[:q])
      @users = @q.result(distinct: true)
      @pagy, @users = pagy(@q.result)
    end

    def show
      authorize User, :show?

      @user = User.find(params[:id])
    end

    def new
      @user = User.new
    end

    def edit; end

    def create
      @user = User.new(user_params)
      respond_to do |format|
        if @user.save
          format.html { redirect_to system_user_path(@user), notice: 'User was successfully created.' }
          format.json { render :show, status: :created, location: @user }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end

    def update
      respond_to do |format|
        if @user.update(user_params)
          format.html { redirect_to system_user_path(@user), notice: 'User was successfully updated.' }
          format.json { render :show, status: :ok, location: @user }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      @user.destroy
      respond_to do |format|
        format.html { redirect_to system_users_path, notice: 'User was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private

    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(policy(User).admin_permitted_attributes)
    end
  end
end

app/views/system/users/_form.html.erb
<%= form_with(model: [:system, user], class: 'contents') do |f| %>
  <div class="max-w-sm bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700">
    <div class="py-8 px-4 mx-auto max-w-2xl">
      <div class="grid gap-4 sm:grid-cols-2 sm:gap-6">
        <div class="sm:col-span-2">
          <%= f.label :first_name, class: 'block mb-2 text-sm font-medium text-gray-900 dark:text-white' %>
          <%= f.text_field :first_name, placeholder: 'First Name', class: 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500' %>
        </div>
        <div class="sm:col-span-2">
          <%= f.label :last_name, class: 'block mb-2 text-sm font-medium text-gray-900 dark:text-white' %>
          <%= f.text_field :last_name, placeholder: 'Last Name', class: 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500' %>
        </div>
        <div class="sm:col-span-2">
          <%= f.label :nickname, class: 'block mb-2 text-sm font-medium text-gray-900 dark:text-white' %>
          <%= f.text_field :nickname, placeholder: 'Nickname', class: 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500' %>
        </div>
        <div class="sm:col-span-2">
          <%= f.label :email, class: 'block mb-2 text-sm font-medium text-gray-900 dark:text-white' %>
          <%= f.text_field :email, placeholder: 'Email', class: 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500' %>
        </div>
        <div class="w-full">
          <%= f.label :password, class: 'block mb-2 text-sm font-medium text-gray-900 dark:text-white' %>
          <%= f.text_field :password, placeholder: 'Password', class: 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500' %>
        </div>
        <div class="w-full">
          <%= f.label :password_confirmation, class: 'block mb-2 text-sm font-medium text-gray-900 dark:text-white' %>
          <%= f.text_field :password_confirmation, placeholder: 'Password Confirmation', class: 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500' %>
        </div>
        <div class="w-full">
          <%= f.label :phone_number, class: 'block mb-2 text-sm font-medium text-gray-900 dark:text-white' %>
          <%= f.text_field :phone_number, placeholder: 'Phone Number', class: 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500' %>
        </div>
        <div class="w-full">
          <%= f.label :role, class: 'block mb-2 text-sm font-medium text-gray-900 dark:text-white' %>
          <%= f.select :role, User.role.values, {}, class: 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500' %>
        </div>
        <div class="sm:col-span-2">
          <% if @user.avatar.present? %>
            <%= image_tag @user.avatar, class: 'w-20 h-20 object-cover rounded-md mt-1' %>
          <% end %>
          <%= f.label :avatar, class: 'block mb-2 text-sm font-medium text-gray-900 dark:text-white' %>
          <%= f.file_field :avatar, class: 'block w-full text-sm text-gray-900 border border-gray-300 rounded-lg cursor-pointer bg-gray-100 dark:text-gray-400 focus:outline-none dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400' %>
        </div>
      </div>
      <%= f.submit class: 'inline-flex items-center px-5 py-2.5 mt-4 sm:mt-6 text-sm font-medium text-center text-white bg-primary-700 rounded-lg focus:ring-4 focus:ring-primary-200 dark:focus:ring-primary-900 hover:bg-primary-800' %>
      <%= link_to 'Back', system_user_path(user), class: 'inline-flex items-center px-5 py-2.5 mt-4 sm:mt-6 text-sm font-medium text-center text-white bg-primary-700 rounded-lg focus:ring-4 focus:ring-primary-200 dark:focus:ring-primary-900 hover:bg-primary-800' %>
    </div>
  </div>
<% end %>

app/views/system/users/_search_form.html.erb
<%= search_form_for @q, url: system_users_path, method: :get, class: 'flex items-center max-w-lg mx-auto' do |f| %>
  <div class="relative w-full">
    <div class="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none">
      <svg aria-hidden="true" class="w-5 h-5 text-gray-500 dark:text-gray-400" fill="currentColor"
        viewbox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
        <path fill-rule="evenodd"
          d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z"
          clip-rule="evenodd" />
      </svg>
    </div>
    <%= f.search_field :email_or_first_name_or_last_name_or_nickname_or_role_cont,
      class: 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full ps-10 p-2.5  dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500',
      placeholder: 'Search' %>
  </div>
  <%= f.submit 'Search', class: 'flex items-center justify-center text-white bg-primary-700 hover:bg-primary-800 focus:ring-4 focus:ring-primary-300 font-medium rounded-lg text-sm px-4 py-2 dark:bg-primary-600 dark:hover:bg-primary-700 focus:outline-none dark:focus:ring-primary-800 ms-2' %>
  <%= link_to 'Reset', system_users_path, class: 'flex items-center justify-center text-white bg-primary-700 hover:bg-primary-800 focus:ring-4 focus:ring-primary-300 font-medium rounded-lg text-sm px-4 py-2 dark:bg-primary-600 dark:hover:bg-primary-700 focus:outline-none dark:focus:ring-primary-800 ms-2' %>
<% end %>

app/views/system/users/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="mb-4 text-3xl font-extrabold text-gray-900 dark:text-white md:text-5xl lg:text-6xl text-center">
    <span class="text-transparent bg-clip-text bg-gradient-to-r to-emerald-600 from-sky-400">
      Edit User
    </span>  
  </h1>
  <div class="flex justify-center px-4 mx-auto max-w-screen-xl mb-10">
    <%= render 'form', user: @user %>
  </div>
</div>

app/views/system/users/index.html.erb
<section class="bg-gray-50 dark:bg-gray-900 p-3 sm:p-5">
  <div class="mx-auto px-4 lg:px-12">
    <div class="bg-white dark:bg-gray-800 relative shadow-md sm:rounded-lg overflow-hidden">
      <div class="flex flex-col md:flex-row items-center justify-between space-y-3 md:space-y-0 md:space-x-4 p-4">
        <div class="w-full md:w-1/2">
          <%= render 'search_form', ransack: @q %>
        </div>
        <div class="w-full md:w-auto flex flex-col md:flex-row space-y-2 md:space-y-0 items-stretch md:items-center justify-end md:space-x-3 flex-shrink-0">
          <%= link_to new_system_user_path, class: 'flex items-center justify-center text-white bg-primary-700 hover:bg-primary-800 focus:ring-4 focus:ring-primary-300 font-medium rounded-lg text-sm px-4 py-2 dark:bg-primary-600 dark:hover:bg-primary-700 focus:outline-none dark:focus:ring-primary-800' do %>
           <svg class="h-3.5 w-3.5 mr-2" fill="currentColor" viewbox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"
              aria-hidden="true">
              <path clip-rule="evenodd" fill-rule="evenodd"
                d="M10 3a1 1 0 011 1v5h5a1 1 0 110 2h-5v5a1 1 0 11-2 0v-5H4a1 1 0 110-2h5V4a1 1 0 011-1z" />
            </svg>
            New User
         <% end %>
        </div>
      </div>
      <div class="overflow-x-auto">
        <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
          <thead class="text-xs text-gray-700 uppercase bg-gray-100 dark:bg-gray-700 dark:text-gray-400">
            <tr>
              <th scope="col" class="px-4 py-3"><%= sort_link @q, :id %></th>
              <th scope="col" class="px-4 py-3"><%= sort_link @q, :first_name %></th>
              <th scope="col" class="px-4 py-3"><%= sort_link @q, :last_name %></th>
              <th scope="col" class="px-4 py-3"><%= sort_link @q, :nickname %></th>
              <th scope="col" class="px-4 py-3"><%= sort_link @q, :email %></th>
              <th scope="col" class="px-4 py-3"><%= sort_link @q, :phone_number %></th>
              <th scope="col" class="px-4 py-3"><%= sort_link @q, :role %></th>
              <th scope="col" class="px-4 py-3">
                <span class="sr-only">Actions</span>
              </th>
            </tr>
          </thead>
          <tbody>
            <% @users.order(id: :desc).each do |user| %>
              <tr class="border-b dark:border-gray-700">
                <th scope="row" class="px-4 py-3 font-medium text-gray-900 whitespace-nowrap dark:text-white"><%= link_to user.id, system_user_path(user) %></th>
                <td class="px-4 py-3"><%= user.first_name %></td>
                <td class="px-4 py-3"><%= user.last_name %></td>
                <td class="px-4 py-3"><%= user.nickname %></td>
                <td class="px-4 py-3"><%= user.email %></td>
                <td class="px-4 py-3"><%= user.phone_number %></td>
                <td class="px-4 py-3"><%= user.role %></td>
                <td class="px-4 py-3 flex items-center justify-end">
                  <button id="<%= user.id %>-button" data-dropdown-toggle="<%= user.id %>"
                    class="inline-flex items-center p-0.5 text-sm font-medium text-center text-gray-500 hover:text-gray-800 rounded-lg focus:outline-none dark:text-gray-400 dark:hover:text-gray-100"
                    type="button">
                    <svg class="w-5 h-5" aria-hidden="true" fill="currentColor" viewbox="0 0 20 20"
                      xmlns="http://www.w3.org/2000/svg">
                      <path
                        d="M6 10a2 2 0 11-4 0 2 2 0 014 0zM12 10a2 2 0 11-4 0 2 2 0 014 0zM16 12a2 2 0 100-4 2 2 0 000 4z" />
                    </svg>
                  </button>
                  <div id="<%= user.id %>"
                    class="hidden z-10 w-22 bg-white rounded divide-y divide-gray-100 shadow dark:bg-gray-700 dark:divide-gray-600">
                    <ul class="py-1 text-sm text-gray-700 dark:text-gray-200"
                      aria-labelledby="<%= user.id %>-button">
                      <li>
                        <%= link_to 'Edit', edit_system_user_path(user), class: 'block py-2 px-4 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white' %>
                      </li>
                      <hr>
                      <li>
                        <%= button_to 'Destroy', system_user_path(user), method: :delete, class: 'block py-2 px-4 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white' %>
                      </li>
                    </ul>
                  </div>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <%= render 'shared/paginate' %>
    </div>
  </div>
</section>

app/views/system/users/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="mb-4 text-3xl font-extrabold text-gray-900 dark:text-white md:text-5xl lg:text-6xl text-center">
    <span class="text-transparent bg-clip-text bg-gradient-to-r to-emerald-600 from-sky-400">
      New User
    </span>  
  </h1>
  <div class="flex justify-center px-4 mx-auto max-w-screen-xl mb-10">
    <%= render 'form', user: @user %>
  </div>
</div>

app/views/system/users/show.html.erb
<div class="flex justify-center px-4 mx-auto max-w-screen-xl mb-10 mt-2">
  <div class="max-w-sm bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700">
    <%= render 'shared/page_heading', model: @user %>
    <hr>
    <div class="py-4 px-10 mx-auto">
      <%= @user.avatar.present? ? image_tag(@user.avatar.variant(:thumb)) : image_tag('https://via.placeholder.com/50') %>
    </div>
    <div class="py-4 px-4 mx-auto">
      <h2 class="mb-2 text-xl font-semibold leading-none text-gray-900 md:text-2xl dark:text-white"><%= @user.display_name %></h2>
      <p class="mb-4 text-xl font-extrabold leading-none text-gray-900 md:text-2xl dark:text-white">@<%= @user.nickname %></p>
      <dl>
        <dt class="mb-2 font-semibold leading-none text-gray-900 dark:text-white">Email:</dt>
        <dd class="mb-4 font-light text-gray-500 sm:mb-5 dark:text-gray-400"><%= @user.email %></dd>
      </dl>
      <dl class="flex items-center space-x-6">
        <div>
          <dt class="mb-2 font-semibold leading-none text-gray-900 dark:text-white">Phone:</dt>
          <dd class="mb-4 font-light text-gray-500 sm:mb-5 dark:text-gray-400"><%= @user.phone_number %></dd>
        </div>
        <div>
          <dt class="mb-2 font-semibold leading-none text-gray-900 dark:text-white">Role:</dt>
          <dd class="mb-4 font-light text-gray-500 sm:mb-5 dark:text-gray-400"><%= @user.role %></dd>
        </div>
      </dl>
      <dl class="flex items-center space-x-6">
        <div>
          <dt class="mb-2 font-semibold leading-none text-gray-900 dark:text-white">UID:</dt>
          <dd class="mb-4 font-light text-gray-500 sm:mb-5 dark:text-gray-400"><%= @user.uid %></dd>
        </div>
        <div>
          <dt class="mb-2 font-semibold leading-none text-gray-900 dark:text-white">Provider:</dt>
          <dd class="mb-4 font-light text-gray-500 sm:mb-5 dark:text-gray-400"><%= @user.provider %></dd>
        </div>
      </dl>
      <div class="flex items-center space-x-6">
        <%= link_to edit_system_user_path(@user), class: 'text-white inline-flex items-center bg-primary-700 hover:bg-primary-800 focus:ring-4 focus:outline-none focus:ring-primary-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-primary-600 dark:hover:bg-primary-700 dark:focus:ring-primary-800' do %>
          <svg aria-hidden="true" class="mr-1 -ml-1 w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M17.414 2.586a2 2 0 00-2.828 0L7 10.172V13h2.828l7.586-7.586a2 2 0 000-2.828z"></path><path fill-rule="evenodd" d="M2 6a2 2 0 012-2h4a1 1 0 010 2H4v10h10v-4a1 1 0 112 0v4a2 2 0 01-2 2H4a2 2 0 01-2-2V6z" clip-rule="evenodd"></path></svg>
          Edit
        <% end %>
        <%= button_to system_user_path(@user), method: :delete, data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'}, class: 'inline-flex items-center text-white bg-red-600 hover:bg-red-700 focus:ring-4 focus:outline-none focus:ring-red-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-red-500 dark:hover:bg-red-600 dark:focus:ring-red-900' do %>
          <svg aria-hidden="true" class="w-5 h-5 mr-1.5 -ml-1" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 0 102 0V8a1 1 0 00-1-1z" clip-rule="evenodd"></path></svg>
          Delete
        <% end %>
      </div>
    </div>
  </div>
</div>