config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  unauthenticated do
    root to: 'home#index', as: :unauthenticated_root
  end

  authenticated :user do
    constraints ->(req) { req.env['warden'].user.role == 'admin' } do
      root to: 'system/dashboard#index', as: :admin_root
    end

    root to: 'main/posts#index'
  end

  namespace :system do
    resources :users
    resources :posts do
      member do
        put 'post_published'
        put 'cancel'
      end
    end
  end

  namespace :main do
    resources :users, except: %i[index create new]
    resources :posts do
      member do
        put 'post_published'
        put 'cancel'
      end
    end
  end

  devise_for :users, path: 'auth', controllers: {
    registrations: 'auth/registrations',
    omniauth_callbacks: 'auth/omniauth_callbacks'
  }
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  include AASM
  extend Enumerize

  belongs_to :user

  has_many_attached :images do |attachable|
    attachable.variant :thumb, resize_to_limit: [300, 300]
  end

  enumerize :post_type,
            in: %i[text_post selling],
            default: :text_post,
            predicates: true,
            scope: true

  scope :published_or_pending_for_user, lambda { |user_id|
    where("status = 'published' OR (user_id = ? AND status = 'pending') OR (user_id = ? AND status = 'cancelled')", user_id, user_id)
  }

  def self.ransackable_attributes(_auth_object = nil)
    %w[created_at id id_value note status updated_at user_id]
  end

  def self.ransackable_associations(_auth_object = nil)
    ['user']
  end

  aasm :status, no_direct_assignment: true do
    state :pending, initial: true
    state :pending, :published, :cancelled

    event :make_published do
      transitions from: %i[pending cancelled], to: :published
    end

    event :cancel do
      transitions from: %i[pending published], to: :cancelled
    end
  end
end

app/controllers/main/application_controller.rb
# frozen_string_literal: true

module Main
  class ApplicationController < ::ApplicationController
    before_action :authenticate_user!

    layout 'main'
  end
end

app/controllers/main/home_controller.rb
# frozen_string_literal: true

module Main
  class HomeController < Main::ApplicationController
    def index; end
  end
end

app/controllers/main/posts_controller.rb
# frozen_string_literal: true

module Main
  class PostsController < Main::ApplicationController
    before_action :set_post, only: %i[show edit update destroy post_published cancel]

    def index
      @pagy, @posts = pagy_countless(Post.published_or_pending_for_user(current_user.id).order(created_at: :desc), items: 10)

      render 'scrollable_list' if params[:page]
    end

    def show; end

    def new
      @post = current_user.posts.build
    end

    def edit
      authorize @post, :edit?
    end

    def create
      @post = current_user.posts.build(post_params)

      respond_to do |format|
        if @post.save
          format.html { redirect_to main_post_url(@post), notice: 'Post was successfully created.' }
          format.json { render :show, status: :created, location: @post }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end

    def update
      authorize @post, :update?

      respond_to do |format|
        if @post.update(post_params)
          format.html { redirect_to main_post_url(@post), notice: 'Post was successfully updated.' }
          format.json { render :show, status: :ok, location: @post }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      authorize @post, :destroy?

      @post.destroy!

      respond_to do |format|
        format.html { redirect_to main_posts_url, notice: 'Post was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    def post_published
      authorize @post, :update?

      @post = Post.find(params[:id])

      @post.make_published!
      flash[:success] = 'Your post has been published.'
      redirect_to main_post_path(@post)
    end

    def cancel
      authorize @post, :update?

      @post = Post.find(params[:id])

      @post.cancel!
      flash[:success] = 'Your post has been cancelled.'
      redirect_to main_post_path(@post)
    end

    private

    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(policy(Post).permitted_attributes)
    end
  end
end

app/controllers/main/users_controller.rb
# frozen_string_literal: true

module Main
  class UsersController < Main::ApplicationController
    before_action :set_user, only: %i[show edit update destroy]

    def show
      @user = User.find(params[:id])
      @post = Post.where(user_id: @user)
    end

    def edit
      authorize @user, :edit?
    end

    def update
      authorize @user, :update?

      respond_to do |format|
        if @user.update(user_params)
          format.html { redirect_to main_user_path(@user), notice: 'Your profile was successfully updated.' }
          format.json { render :show, status: :ok, location: @user }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      authorize @user, :destroy?

      @user.destroy
      respond_to do |format|
        format.html { redirect_to unauthenticated_root_path, notice: 'User was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private

    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(policy(User).permitted_attributes)
    end
  end
end

app/controllers/system/posts_controller.rb
# frozen_string_literal: true

module System
  class PostsController < System::ApplicationController
    before_action :set_post, only: %i[show edit update destroy]

    def index
      @q = Post.ransack(params[:q])
      @posts = @q.result(distinct: true)
      @pagy, @posts = pagy(@q.result)
    end

    def show; end

    def new
      @post = current_user.posts.build
    end

    def edit; end

    def create
      @post = current_user.posts.build(post_params)

      respond_to do |format|
        if @post.save
          format.html { redirect_to system_post_url(@post), notice: 'Post was successfully created.' }
          format.json { render :show, status: :created, location: @post }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end

    def update
      respond_to do |format|
        if @post.update(post_params)
          format.html { redirect_to system_post_url(@post), notice: 'Post was successfully updated.' }
          format.json { render :show, status: :ok, location: @post }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      @post.destroy!

      respond_to do |format|
        format.html { redirect_to system_posts_url, notice: 'Post was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    def post_published
      @post = Post.find(params[:id])

      @post.make_published!
      flash[:success] = "Post #{@post.id} has been published."
      redirect_to system_post_path(@post)
    end

    def cancel
      @post = Post.find(params[:id])

      @post.cancel!
      flash[:success] = "Post #{@post.id} has been cancelled."
      redirect_to system_post_path(@post)
    end

    private

    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(policy(Post).permitted_attributes)
    end
  end
end

app/views/main/posts/_form.html.erb
<% if @post.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@post.errors.count, 'error') %> prohibited this post from being saved:</h2>
    <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= turbo_frame_tag post do %>
  <%= form_with(model: [:main, post], class: 'contents') do |f| %>
    <div class="flex flex-col items-center bg-white border border-gray-200 rounded-lg shadow md:flex-row md:max-w-xl hover:bg-gray-100 dark:border-gray-700 dark:bg-gray-800 dark:hover:bg-gray-700 mt-2">
      <div class="flex flex-col justify-between p-4 leading-normal">
        <div>
          <%= f.label :note, class: 'block mb-2 text-sm font-medium text-gray-900 dark:text-white' %>
          <%= f.text_area :note, class: 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500' %>
        </div>
        <div>
          <%= f.label :post_type, class: 'block mb-2 text-sm font-medium text-gray-900 dark:text-white' %>
          <%= f.select :post_type, Post.post_type.values, { id: 'post_post_type' }, class: 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500' %>
        </div>
        <div id="post_price_field">
          <%= f.label :price, class: 'block mb-2 text-sm font-medium text-gray-900 dark:text-white' %>
          <%= f.text_field :price, class: 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500' %>
        </div>
        <div>
          <% if @post.persisted? && @post.images.any? %>
            <% @post.images.each do |image| %>
              <%= image_tag image, class: 'w-20 h-20 object-cover rounded-md mt-1' %>
            <% end %>
          <% end %>
          <%= f.label :images, class: 'block mb-2 text-sm font-medium text-gray-900 dark:text-white' %>
          <%= f.file_field :images, class: 'block w-full text-sm text-gray-900 border border-gray-300 rounded-lg cursor-pointer bg-gray-100 dark:text-gray-400 focus:outline-none dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400' %>
        </div>
        <div>
          <%= f.submit class: 'inline-flex items-center px-5 py-2.5 mt-4 sm:mt-6 text-sm font-medium text-center text-white bg-primary-700 rounded-lg focus:ring-4 focus:ring-primary-200 dark:focus:ring-primary-900 hover:bg-primary-800' %>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/main/posts/_next_page.html.erb
<%= turbo_frame_tag("posts-page-#{@pagy.next}", loading: :lazy, src: pagy_url_for(@pagy, @pagy.next), target: '_top') do %>
  Loading...
<% end %>

app/views/main/posts/_post.html.erb
<%= link_to main_post_path(post), class: 'flex flex-col items-center bg-white border border-gray-200 rounded-lg shadow md:flex-row md:max-w-xl hover:bg-gray-100 dark:border-gray-700 dark:bg-gray-800 dark:hover:bg-gray-700' do %>
  <div class="flex-shrink-0 mr-4">
    <% if post.images.present? %>
      <% post.images.each do |image| %>
        <%= image_tag image, class: 'object-cover w-full rounded-t-lg h-98 md:h-auto md:w-48 md:rounded-none md:rounded-s-lg' %>
      <% end %>
    <% end %>
  </div>
  <div class="flex flex-col justify-between p-4 leading-normal">
    <h5 class="text-2xl font-bold tracking-tight text-gray-900 dark:text-white"><%= post.user&.display_name %></h5>
    <p class="mb-3 font-normal text-gray-700 dark:text-gray-400">@<%= post.user.nickname %></p>
    <p class="mb-3 font-normal text-gray-700 dark:text-gray-400"><%= post.note %></p>
    <% if post.selling? %>
      <p class="mb-3 font-normal text-gray-700 dark:text-gray-400"><%= post.price %>$</p>
      <div class="max-w-sm">
        <button type="button" class="px-3 py-2 text-xs font-medium text-center text-white bg-gradient-to-r from-green-400 via-green-500 to-green-600 hover:bg-gradient-to-br focus:outline-none focus:ring-4 focus:ring-green-300 font-medium rounded-full text-sm px-5 py-2.5 text-center me-2 mb-2 dark:bg-green-600 dark:hover:bg-green-700 dark:focus:ring-green-800">Buy</button>
      </div>
    <% end %>
    <% if post.may_make_published? %>
      <%= button_to 'Publish', post_published_main_post_path(post), method: :put, class: 'underline dark:text-white' %>
    <% end %>
  </div>
<% end %>

app/views/main/posts/edit.html.erb
<div class="mx-auto md:w-2/3 w-full mb-6">
  <h1 class="font-bold text-4xl">Editing post</h1>

  <%= render 'form', post: @post %>
</div>

app/views/main/posts/index.html.erb
<div class="w-full">
  <section class="bg-gray-50 dark:bg-gray-900 p-3 sm:p-5">
    <div class="flex justify-center items-center">
      <%= link_to 'New Post', new_main_post_path, class: 'rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium',
        data: {turbo_frame: dom_id(Post.new)} %>
    </div>
    <div class="flex justify-center items-center">
      <%= turbo_frame_tag Post.new %>
    </div>

    <div class="flex justify-center items-center">
      <div id="posts" class="grid grid-cols-1 gap-2 m-4">
        <%= render partial: 'post', collection: @posts %>
        <%= render partial: 'next_page' %>
      </div>
    </div>
  </section>
</div>

app/views/main/posts/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New post</h1>

  <%= render 'form', post: @post %>
</div>

app/views/main/posts/scrollable_list.html.erb
<%= turbo_frame_tag "posts-page-#{@pagy.page}" do %>
  <%= render partial: 'post', collection: @posts %>
  <%= render partial: 'next_page' %>
<% end %>

app/views/main/posts/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex mt-2 mb-2">
  <div class="mx-auto">
    <div class="max-w-sm bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700">
      <% if @post.images.present? %>
        <% @post.images.each do |image| %>
          <%= image_tag image, class: 'rounded-t-lg' %>
        <% end %>
      <% end %>
      <div class="p-5">
        <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white"><%= @post.user&.display_name %></h5>
        <p class="font-normal text-gray-700 dark:text-gray-400">@<%= link_to @post.user.nickname, main_user_path(@post.user), class: 'text-blue-700' %> | Status: <%= @post.status %></p>
        <p class="mt-3 font-normal text-gray-700 dark:text-gray-400"><%= @post.note %></p>
        <% if @post.selling? %>
          <p class="mb-3 font-normal text-gray-700 dark:text-gray-400"><%= @post.price %>$</p>
          <div class="max-w-sm">
            <button type="button" class="px-3 py-2 text-xs font-medium text-center text-white bg-gradient-to-r from-green-400 via-green-500 to-green-600 hover:bg-gradient-to-br focus:outline-none focus:ring-4 focus:ring-green-300 font-medium rounded-full text-sm px-5 py-2.5 text-center me-2 mb-2 dark:bg-green-600 dark:hover:bg-green-700 dark:focus:ring-green-800">Buy</button>
          </div>
        <% end %>
      </div>
      <div class="px-4 py-3 flex items-center justify-between">
        <% if current_user.id == @post.user_id %>
          <%= render partial: 'shared/status_actions', locals: { post: @post, namespace: params[:controller].split('/').first } %>
          <button id="<%= @post.id %>-button" data-dropdown-toggle="<%= @post.id %>" class="inline-flex items-center p-0.5 text-sm font-medium text-center text-gray-500 hover:text-gray-800 rounded-lg focus:outline-none dark:text-gray-400 dark:hover:text-gray-100" type="button">
            <svg class="w-5 h-5" aria-hidden="true" fill="currentColor" viewbox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
              <path d="M6 10a2 2 0 11-4 0 2 2 0 014 0zM12 10a2 2 0 11-4 0 2 2 0 014 0zM16 12a2 2 0 100-4 2 2 0 000 4z" />
            </svg>
          </button>
          <div id="<%= @post.id %>" class="hidden z-10 w-22 bg-white rounded divide-y divide-gray-100 shadow dark:bg-gray-700 dark:divide-gray-600">
            <ul class="py-1 text-sm text-gray-700 dark:text-gray-200" aria-labelledby="<%= @post.id %>-button">
              <li>
                <%= link_to 'Edit', edit_main_post_path(@post), class: 'block py-2 px-4 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white' %>
              </li>
              <hr>
              <li>
                <%= button_to 'Destroy', main_post_path(@post), method: :delete, class: 'block py-2 px-4 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white' %>
              </li>
              <hr>
              <li>
                <%= link_to 'Back', main_posts_path, class: 'block py-2 px-4 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white' %>
              </li>
            </ul>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>