config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  unauthenticated do
    root to: 'home#index', as: :unauthenticated_root
  end

  authenticated :user do
    constraints ->(req) { req.env['warden'].user.role == 'admin' } do
      root to: 'system/dashboard#index', as: :admin_root
    end

    root to: 'main/posts#index'
  end

  namespace :system do
    resources :users
    resources :posts do
      member do
        put 'post_published'
        put 'cancel'
      end
    end
  end

  namespace :main do
    resources :users, except: %i[index create new]
    resources :posts do
      member do
        put 'post_published'
        put 'cancel'
      end
    end
  end

  devise_for :users, path: 'auth', controllers: {
    registrations: 'auth/registrations',
    omniauth_callbacks: 'auth/omniauth_callbacks'
  }
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  include AASM
  extend Enumerize

  belongs_to :user

  has_many_attached :images do |attachable|
    attachable.variant :thumb, resize_to_limit: [300, 300]
  end

  enumerize :post_type,
            in: %i[text_post selling],
            default: :text_post,
            predicates: true,
            scope: true

  scope :published_or_pending_for_user, lambda { |user_id|
    where("status = 'published' OR (user_id = ? AND status = 'pending') OR (user_id = ? AND status = 'cancelled')", user_id, user_id)
  }

  def self.ransackable_attributes(_auth_object = nil)
    %w[created_at id id_value note status updated_at user_id]
  end

  def self.ransackable_associations(_auth_object = nil)
    ['user']
  end

  aasm :status, no_direct_assignment: true do
    state :pending, initial: true
    state :pending, :published, :cancelled

    event :make_published do
      transitions from: %i[pending cancelled], to: :published
    end

    event :cancel do
      transitions from: %i[pending published], to: :cancelled
    end
  end
end

app/controllers/main/posts_controller.rb
# frozen_string_literal: true

module Main
  class PostsController < Main::ApplicationController
    before_action :set_post, only: %i[show edit update destroy post_published cancel]

    def index
      @pagy, @posts = pagy_countless(Post.published_or_pending_for_user(current_user.id).order(created_at: :desc), items: 10)

      render 'scrollable_list' if params[:page]
    end

    def show; end

    def new
      @post = current_user.posts.build
    end

    def edit
      authorize @post, :edit?
    end

    def create
      @post = current_user.posts.build(post_params)

      respond_to do |format|
        if @post.save
          format.html { redirect_to main_post_url(@post), notice: 'Post was successfully created.' }
          format.json { render :show, status: :created, location: @post }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end

    def update
      authorize @post, :update?

      respond_to do |format|
        if @post.update(post_params)
          format.html { redirect_to main_post_url(@post), notice: 'Post was successfully updated.' }
          format.json { render :show, status: :ok, location: @post }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      authorize @post, :destroy?

      @post.destroy!

      respond_to do |format|
        format.html { redirect_to main_posts_url, notice: 'Post was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    def post_published
      authorize @post, :update?

      @post = Post.find(params[:id])

      @post.make_published!
      flash[:success] = 'Your post has been published.'
      redirect_to main_post_path(@post)
    end

    def cancel
      authorize @post, :update?

      @post = Post.find(params[:id])

      @post.cancel!
      flash[:success] = 'Your post has been cancelled.'
      redirect_to main_post_path(@post)
    end

    private

    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(policy(Post).permitted_attributes)
    end
  end
end

app/controllers/system/application_controller.rb
# frozen_string_literal: true

module System
  class ApplicationController < ::ApplicationController
    before_action :authenticate_user!
    before_action :redirect_user

    layout 'system'

    private

    def redirect_user
      return unless user_signed_in? && !current_user.admin? && !devise_controller?

      flash[:error] = 'You do not have permission to go to administrative pages!'

      redirect_to main_posts_path
    end
  end
end

app/controllers/system/dashboard_controller.rb
# frozen_string_literal: true

module System
  class DashboardController < System::ApplicationController
    def index; end
  end
end

app/controllers/system/posts_controller.rb
# frozen_string_literal: true

module System
  class PostsController < System::ApplicationController
    before_action :set_post, only: %i[show edit update destroy]

    def index
      @q = Post.ransack(params[:q])
      @posts = @q.result(distinct: true)
      @pagy, @posts = pagy(@q.result)
    end

    def show; end

    def new
      @post = current_user.posts.build
    end

    def edit; end

    def create
      @post = current_user.posts.build(post_params)

      respond_to do |format|
        if @post.save
          format.html { redirect_to system_post_url(@post), notice: 'Post was successfully created.' }
          format.json { render :show, status: :created, location: @post }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end

    def update
      respond_to do |format|
        if @post.update(post_params)
          format.html { redirect_to system_post_url(@post), notice: 'Post was successfully updated.' }
          format.json { render :show, status: :ok, location: @post }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      @post.destroy!

      respond_to do |format|
        format.html { redirect_to system_posts_url, notice: 'Post was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    def post_published
      @post = Post.find(params[:id])

      @post.make_published!
      flash[:success] = "Post #{@post.id} has been published."
      redirect_to system_post_path(@post)
    end

    def cancel
      @post = Post.find(params[:id])

      @post.cancel!
      flash[:success] = "Post #{@post.id} has been cancelled."
      redirect_to system_post_path(@post)
    end

    private

    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(policy(Post).permitted_attributes)
    end
  end
end

app/controllers/system/users_controller.rb
# frozen_string_literal: true

module System
  class UsersController < ApplicationController
    before_action :set_user, only: %i[show edit update destroy]

    def index
      authorize User, :index?

      @q = User.ransack(params[:q])
      @users = @q.result(distinct: true)
      @pagy, @users = pagy(@q.result)
    end

    def show
      authorize User, :show?

      @user = User.find(params[:id])
    end

    def new
      @user = User.new
    end

    def edit; end

    def create
      @user = User.new(user_params)
      respond_to do |format|
        if @user.save
          format.html { redirect_to system_user_path(@user), notice: 'User was successfully created.' }
          format.json { render :show, status: :created, location: @user }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end

    def update
      respond_to do |format|
        if @user.update(user_params)
          format.html { redirect_to system_user_path(@user), notice: 'User was successfully updated.' }
          format.json { render :show, status: :ok, location: @user }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      @user.destroy
      respond_to do |format|
        format.html { redirect_to system_users_path, notice: 'User was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private

    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(policy(User).admin_permitted_attributes)
    end
  end
end

app/views/system/posts/_form.html.erb
<% if @post.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@post.errors.count, 'error') %> prohibited this post from being saved:</h2>
    <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: [:system, post], class: 'contents') do |f| %>
  <div class="max-w-sm bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700">
    <div class="py-8 px-4 mx-auto max-w-2xl">
      <div class="grid gap-4 sm:grid-cols-2 sm:gap-6">
        <div class="sm:col-span-2">
          <%= f.label :note, class: 'block mb-2 text-sm font-medium text-gray-900 dark:text-white' %>
          <%= f.text_area :note, class: 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500' %>
        </div>
        <div class="sm:col-span-2">
          <%= f.label :post_type, class: 'block mb-2 text-sm font-medium text-gray-900 dark:text-white' %>
          <%= f.select :post_type, Post.post_type.values, { id: 'post_post_type' }, class: 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500' %>
        </div>
        <div class="sm:col-span-2" id="post_price_field">
          <%= f.label :price, class: 'block mb-2 text-sm font-medium text-gray-900 dark:text-white' %>
          <%= f.text_field :price, class: 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500' %>
        </div>
        <div class="sm:col-span-2">
          <% if @post.persisted? && @post.images.any? %>
            <% @post.images.each do |image| %>
              <%= image_tag image, class: 'w-20 h-20 object-cover rounded-md mt-1' %>
            <% end %>
          <% end %>
          <%= f.label :images, class: 'block mb-2 text-sm font-medium text-gray-900 dark:text-white' %>
          <%= f.file_field :images, class: 'block w-full text-sm text-gray-900 border border-gray-300 rounded-lg cursor-pointer bg-gray-100 dark:text-gray-400 focus:outline-none dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400' %>
        </div>
      </div>
      <%= f.submit class: 'inline-flex items-center px-5 py-2.5 mt-4 sm:mt-6 text-sm font-medium text-center text-white bg-primary-700 rounded-lg focus:ring-4 focus:ring-primary-200 dark:focus:ring-primary-900 hover:bg-primary-800' %>
      <%= link_to 'Back', system_posts_path, class: 'inline-flex items-center px-5 py-2.5 mt-4 sm:mt-6 text-sm font-medium text-center text-white bg-primary-700 rounded-lg focus:ring-4 focus:ring-primary-200 dark:focus:ring-primary-900 hover:bg-primary-800' %>
    </div>
  </div>
<% end %>

app/views/system/posts/_search_form.html.erb
<%= search_form_for @q, url: system_posts_path, method: :get, class: 'flex items-center max-w-lg mx-auto' do |f| %>
  <div class="relative w-full">
    <div class="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none">
      <svg aria-hidden="true" class="w-5 h-5 text-gray-500 dark:text-gray-400" fill="currentColor"
        viewbox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
        <path fill-rule="evenodd"
          d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z"
          clip-rule="evenodd" />
      </svg>
    </div>
    <%= f.search_field :note_or_status_cont,
      class: 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full ps-10 p-2.5  dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500',
      placeholder: 'Search' %>
  </div>
  <%= f.submit 'Search', class: 'flex items-center justify-center text-white bg-primary-700 hover:bg-primary-800 focus:ring-4 focus:ring-primary-300 font-medium rounded-lg text-sm px-4 py-2 dark:bg-primary-600 dark:hover:bg-primary-700 focus:outline-none dark:focus:ring-primary-800 ms-2' %>
  <%= link_to 'Reset', system_posts_path, class: 'flex items-center justify-center text-white bg-primary-700 hover:bg-primary-800 focus:ring-4 focus:ring-primary-300 font-medium rounded-lg text-sm px-4 py-2 dark:bg-primary-600 dark:hover:bg-primary-700 focus:outline-none dark:focus:ring-primary-800 ms-2' %>
<% end %>

app/views/system/posts/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="mb-4 text-3xl font-extrabold text-gray-900 dark:text-white md:text-5xl lg:text-6xl text-center">
    <span class="text-transparent bg-clip-text bg-gradient-to-r to-emerald-600 from-sky-400">
      Edit Post
      <%= @post.id %>
    </span>  
  </h1>
  <div class="flex justify-center px-4 mx-auto max-w-screen-xl mb-10">
    <%= render 'form', post: @post %>
  </div>
</div>

app/views/system/posts/index.html.erb
<div class="w-full">
  <section class="bg-gray-50 dark:bg-gray-900 p-3 sm:p-5">
    <div class="mx-auto px-4 lg:px-12">
      <div class="bg-white dark:bg-gray-800 relative shadow-md sm:rounded-lg overflow-hidden">
        <div class="flex flex-col md:flex-row items-center justify-between space-y-3 md:space-y-0 md:space-x-4 p-4">
          <div class="w-full md:w-1/2">
            <%= render 'search_form', ransack: @q %>
          </div>
          <div class="w-full md:w-auto flex flex-col md:flex-row space-y-2 md:space-y-0 items-stretch md:items-center justify-end md:space-x-3 flex-shrink-0">
            <%= link_to new_system_post_path, class: 'flex items-center justify-center text-white bg-primary-700 hover:bg-primary-800 focus:ring-4 focus:ring-primary-300 font-medium rounded-lg text-sm px-4 py-2 dark:bg-primary-600 dark:hover:bg-primary-700 focus:outline-none dark:focus:ring-primary-800' do %>
            <svg class="h-3.5 w-3.5 mr-2" fill="currentColor" viewbox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"
                aria-hidden="true">
                <path clip-rule="evenodd" fill-rule="evenodd"
                  d="M10 3a1 1 0 011 1v5h5a1 1 0 110 2h-5v5a1 1 0 11-2 0v-5H4a1 1 0 110-2h5V4a1 1 0 011-1z" />
              </svg>
              New Post
          <% end %>
          </div>
        </div>
        <div class="overflow-x-auto">
          <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
            <thead class="text-xs text-gray-700 uppercase bg-gray-100 dark:bg-gray-700 dark:text-gray-400">
              <tr>
                <th scope="col" class="px-4 py-3"><%= sort_link @q, :id %></th>
                <th scope="col" class="px-4 py-3"><%= sort_link @q, :note %></th>
                <th scope="col" class="px-4 py-3"><%= sort_link @q, :status %></th>
                <th scope="col" class="px-4 py-3">User</th>
                <th scope="col" class="px-4 py-3">Type</th>
                <th scope="col" class="px-4 py-3">Price</th>
                <th scope="col" class="px-4 py-3">
                  <span class="sr-only">Actions</span>
                </th>
              </tr>
            </thead>
            <tbody>
              <% @posts.order(id: :desc).each do |post| %>
                <tr class="border-b dark:border-gray-700">
                  <th scope="row" class="px-4 py-3 font-medium text-gray-900 whitespace-nowrap dark:text-white"><%= link_to post.id, system_post_path(post) %></th>
                  <td class="px-4 py-3"><%= post.note %></td>
                  <td class="px-4 py-3"><%= post.status %></td>
                  <td class="px-4 py-3"><%= post.user&.display_name %></td>
                  <td class="px-4 py-3"><%= post.post_type %></td>
                  <td class="px-4 py-3">$<%= post.price %></td>
                  <td class="px-4 py-3 flex items-center justify-end">
                    <button id="<%= post.id %>-button" data-dropdown-toggle="<%= post.id %>"
                      class="inline-flex items-center p-0.5 text-sm font-medium text-center text-gray-500 hover:text-gray-800 rounded-lg focus:outline-none dark:text-gray-400 dark:hover:text-gray-100"
                      type="button">
                      <svg class="w-5 h-5" aria-hidden="true" fill="currentColor" viewbox="0 0 20 20"
                        xmlns="http://www.w3.org/2000/svg">
                        <path
                          d="M6 10a2 2 0 11-4 0 2 2 0 014 0zM12 10a2 2 0 11-4 0 2 2 0 014 0zM16 12a2 2 0 100-4 2 2 0 000 4z" />
                      </svg>
                    </button>
                    <div id="<%= post.id %>"
                      class="hidden z-10 w-22 bg-white rounded divide-y divide-gray-100 shadow dark:bg-gray-700 dark:divide-gray-600">
                      <ul class="py-1 text-sm text-gray-700 dark:text-gray-200"
                        aria-labelledby="<%= post.id %>-button">
                        <li>
                          <%= link_to 'Edit', edit_system_post_path(post), class: 'block py-2 px-4 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white' %>
                        </li>
                        <hr>
                        <li>
                          <%= button_to 'Destroy', system_post_path(post), method: :delete, class: 'block py-2 px-4 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white' %>
                        </li>
                      </ul>
                    </div>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
        <%= render 'shared/paginate' %>
      </div>
    </div>
  </section>
</div>

app/views/system/posts/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="mb-4 text-3xl font-extrabold text-gray-900 dark:text-white md:text-5xl lg:text-6xl text-center">
    <span class="text-transparent bg-clip-text bg-gradient-to-r to-emerald-600 from-sky-400">
      New Post
    </span>  
  </h1>
  <div class="flex justify-center px-4 mx-auto max-w-screen-xl mb-10">
    <%= render 'form', post: @post %>
  </div>
</div>

app/views/system/posts/show.html.erb
<div class="flex justify-center px-4 mx-auto max-w-screen-xl mb-10 mt-2">
  <div class="max-w-sm bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700 text-center">
    <%= render 'shared/page_heading', model: @post %>
    <hr>
    <div class="py-4 px-10 mx-auto">
      <% @post.images.each do |image| %>
        <%= image_tag image, class: "w-auto h-70" %>
      <% end %>
    </div>
    <div class="py-4 px-4 mx-auto">
      <h2 class="mb-2 text-xl font-semibold leading-none text-gray-900 md:text-2xl dark:text-white"><%= @post.user&.display_name %></h2>
      <dl>
        <dd class="mb-4 font-light text-gray-500 sm:mb-5 dark:text-gray-400"><%= @post.note %></dd>
      </dl>
      <dl>
        <div>
          <dt class="mb-2 font-semibold leading-none text-gray-900 dark:text-white">Status:</dt>
          <dd class="bg-green-100 text-green-800 text-xs font-medium me-2 px-2.5 py-0.5 rounded-full dark:bg-green-900 dark:text-green-300">
            <%= @post.status %>
          </dd>
          <dd class="mb-4 font-light text-gray-500 sm:mb-5 dark:text-gray-400"><%= render partial: 'shared/status_actions', locals: { post: @post, namespace: params[:controller].split('/').first } %></dd>
        </div>
      </dl>
      <dl>
        <div>
          <dt class="mb-2 font-semibold leading-none text-gray-900 dark:text-white">User:</dt>
          <dd class="mb-4 font-light text-gray-500 sm:mb-5 dark:text-gray-400"><%= @post.user.id %></dd>
        </div>
      </dl>
      <div class="flex items-center space-x-6">
        <%= link_to edit_system_post_path(@post), class: 'text-white inline-flex items-center bg-primary-700 hover:bg-primary-800 focus:ring-4 focus:outline-none focus:ring-primary-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-primary-600 dark:hover:bg-primary-700 dark:focus:ring-primary-800' do %>
          <svg aria-hidden="true" class="mr-1 -ml-1 w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M17.414 2.586a2 2 0 00-2.828 0L7 10.172V13h2.828l7.586-7.586a2 2 0 000-2.828z"></path><path fill-rule="evenodd" d="M2 6a2 2 0 012-2h4a1 1 0 010 2H4v10h10v-4a1 1 0 112 0v4a2 2 0 01-2 2H4a2 2 0 01-2-2V6z" clip-rule="evenodd"></path></svg>
          Edit
        <% end %>
        <%= button_to system_post_path(@post), method: :delete, data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'}, class: 'inline-flex items-center text-white bg-red-600 hover:bg-red-700 focus:ring-4 focus:outline-none focus:ring-red-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-red-500 dark:hover:bg-red-600 dark:focus:ring-red-900' do %>
          <svg aria-hidden="true" class="w-5 h-5 mr-1.5 -ml-1" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 0 102 0V8a1 1 0 00-1-1z" clip-rule="evenodd"></path></svg>
          Delete
        <% end %>
      </div>
    </div>
  </div>
</div>