config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  unauthenticated do
    root to: 'home#index', as: :unauthenticated_root
  end

  authenticated :user do
    constraints ->(req) { req.env['warden'].user.role == 'admin' } do
      root to: 'system/dashboard#index', as: :admin_root
    end

    root to: 'main/posts#index'
  end

  namespace :system do
    resources :users
    resources :posts do
      member do
        put 'post_published'
        put 'cancel'
      end
    end
  end

  namespace :main do
    resources :users, except: %i[index create new]
    resources :posts do
      member do
        put 'post_published'
        put 'cancel'
      end
    end
  end

  devise_for :users, path: 'auth', controllers: {
    registrations: 'auth/registrations',
    omniauth_callbacks: 'auth/omniauth_callbacks'
  }
end

app/models/user.rb
# frozen_string_literal: true

require 'open-uri'

class User < ApplicationRecord
  extend Enumerize

  has_many :posts

  has_one_attached :avatar do |attachable|
    attachable.variant :thumb, resize_to_limit: [300, 300]
    attachable.variant :min, resize_to_limit: [200, 200]
  end

  validates :first_name,
            :last_name,
            :nickname,
            :role,
            presence: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :trackable, :timeoutable, :confirmable,
         :omniauthable, omniauth_providers: %i[google_oauth2 github]

  enumerize :role,
            in: %i[user admin],
            default: :user,
            predicates: true,
            scope: true

  scope :with_admin_role, -> { where(role: :admin) }
  scope :with_user_role, -> { where(role: :user) }

  def self.ransackable_attributes(_auth_object = nil)
    %w[email first_name id last_name nickname phone_number role]
  end

  def self.ransackable_associations(_auth_object = nil)
    []
  end

  def full_name
    "#{first_name} #{last_name}".titleize
  end

  def display_name
    return email if full_name.blank?

    full_name
  end
end

app/controllers/main/application_controller.rb
# frozen_string_literal: true

module Main
  class ApplicationController < ::ApplicationController
    before_action :authenticate_user!

    layout 'main'
  end
end

app/controllers/main/home_controller.rb
# frozen_string_literal: true

module Main
  class HomeController < Main::ApplicationController
    def index; end
  end
end

app/controllers/main/posts_controller.rb
# frozen_string_literal: true

module Main
  class PostsController < Main::ApplicationController
    before_action :set_post, only: %i[show edit update destroy post_published cancel]

    def index
      @pagy, @posts = pagy_countless(Post.published_or_pending_for_user(current_user.id).order(created_at: :desc), items: 10)

      render 'scrollable_list' if params[:page]
    end

    def show; end

    def new
      @post = current_user.posts.build
    end

    def edit
      authorize @post, :edit?
    end

    def create
      @post = current_user.posts.build(post_params)

      respond_to do |format|
        if @post.save
          format.html { redirect_to main_post_url(@post), notice: 'Post was successfully created.' }
          format.json { render :show, status: :created, location: @post }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end

    def update
      authorize @post, :update?

      respond_to do |format|
        if @post.update(post_params)
          format.html { redirect_to main_post_url(@post), notice: 'Post was successfully updated.' }
          format.json { render :show, status: :ok, location: @post }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      authorize @post, :destroy?

      @post.destroy!

      respond_to do |format|
        format.html { redirect_to main_posts_url, notice: 'Post was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    def post_published
      authorize @post, :update?

      @post = Post.find(params[:id])

      @post.make_published!
      flash[:success] = 'Your post has been published.'
      redirect_to main_post_path(@post)
    end

    def cancel
      authorize @post, :update?

      @post = Post.find(params[:id])

      @post.cancel!
      flash[:success] = 'Your post has been cancelled.'
      redirect_to main_post_path(@post)
    end

    private

    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(policy(Post).permitted_attributes)
    end
  end
end

app/controllers/main/users_controller.rb
# frozen_string_literal: true

module Main
  class UsersController < Main::ApplicationController
    before_action :set_user, only: %i[show edit update destroy]

    def show
      @user = User.find(params[:id])
      @post = Post.where(user_id: @user)
    end

    def edit
      authorize @user, :edit?
    end

    def update
      authorize @user, :update?

      respond_to do |format|
        if @user.update(user_params)
          format.html { redirect_to main_user_path(@user), notice: 'Your profile was successfully updated.' }
          format.json { render :show, status: :ok, location: @user }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      authorize @user, :destroy?

      @user.destroy
      respond_to do |format|
        format.html { redirect_to unauthenticated_root_path, notice: 'User was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private

    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(policy(User).permitted_attributes)
    end
  end
end

app/controllers/system/users_controller.rb
# frozen_string_literal: true

module System
  class UsersController < ApplicationController
    before_action :set_user, only: %i[show edit update destroy]

    def index
      authorize User, :index?

      @q = User.ransack(params[:q])
      @users = @q.result(distinct: true)
      @pagy, @users = pagy(@q.result)
    end

    def show
      authorize User, :show?

      @user = User.find(params[:id])
    end

    def new
      @user = User.new
    end

    def edit; end

    def create
      @user = User.new(user_params)
      respond_to do |format|
        if @user.save
          format.html { redirect_to system_user_path(@user), notice: 'User was successfully created.' }
          format.json { render :show, status: :created, location: @user }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end

    def update
      respond_to do |format|
        if @user.update(user_params)
          format.html { redirect_to system_user_path(@user), notice: 'User was successfully updated.' }
          format.json { render :show, status: :ok, location: @user }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      @user.destroy
      respond_to do |format|
        format.html { redirect_to system_users_path, notice: 'User was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private

    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(policy(User).admin_permitted_attributes)
    end
  end
end

app/views/main/users/_form.html.erb
<%= form_with(model: [:main, user], class: 'contents') do |f| %>
  <div class="max-w-sm bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700">
    <div class="py-8 px-4 mx-auto max-w-2xl">
      <div class="grid gap-4 sm:grid-cols-2 sm:gap-6">
        <div class="sm:col-span-2">
          <%= f.label :first_name, class: 'block mb-2 text-sm font-medium text-gray-900 dark:text-white' %>
          <%= f.text_field :first_name, placeholder: 'First Name', class: 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500' %>
        </div>
        <div class="sm:col-span-2">
          <%= f.label :last_name, class: 'block mb-2 text-sm font-medium text-gray-900 dark:text-white' %>
          <%= f.text_field :last_name, placeholder: 'Last Name', class: 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500' %>
        </div>
        <div class="sm:col-span-2">
          <%= f.label :nickname, class: 'block mb-2 text-sm font-medium text-gray-900 dark:text-white' %>
          <%= f.text_field :nickname, placeholder: 'Nickname', class: 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500' %>
        </div>
        <div class="sm:col-span-2">
          <%= f.label :email, class: 'block mb-2 text-sm font-medium text-gray-900 dark:text-white' %>
          <%= f.text_field :email, placeholder: 'Email', class: 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500' %>
        </div>
        <div class="w-full">
          <%= f.label :password, class: 'block mb-2 text-sm font-medium text-gray-900 dark:text-white' %>
          <%= f.text_field :password, placeholder: 'Password', class: 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500' %>
        </div>
        <div class="w-full">
          <%= f.label :password_confirmation, class: 'block mb-2 text-sm font-medium text-gray-900 dark:text-white' %>
          <%= f.text_field :password_confirmation, placeholder: 'Password Confirmation', class: 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500' %>
        </div>
        <div class="w-full">
          <%= f.label :phone_number, class: 'block mb-2 text-sm font-medium text-gray-900 dark:text-white' %>
          <%= f.text_field :phone_number, placeholder: 'Phone Number', class: 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500' %>
        </div>
        <div class="sm:col-span-2">
          <% if @user.avatar.present? %>
            <%= image_tag @user.avatar, class: 'w-20 h-20 object-cover rounded-md mt-1' %>
          <% end %>
          <%= f.label :avatar, class: 'block mb-2 text-sm font-medium text-gray-900 dark:text-white' %>
          <%= f.file_field :avatar, class: 'block w-full text-sm text-gray-900 border border-gray-300 rounded-lg cursor-pointer bg-gray-100 dark:text-gray-400 focus:outline-none dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400' %>
        </div>
      </div>
      <%= f.submit class: 'inline-flex items-center px-5 py-2.5 mt-4 sm:mt-6 text-sm font-medium text-center text-white bg-primary-700 rounded-lg focus:ring-4 focus:ring-primary-200 dark:focus:ring-primary-900 hover:bg-primary-800' %>
      <%= link_to 'Back', system_user_path(user), class: 'inline-flex items-center px-5 py-2.5 mt-4 sm:mt-6 text-sm font-medium text-center text-white bg-primary-700 rounded-lg focus:ring-4 focus:ring-primary-200 dark:focus:ring-primary-900 hover:bg-primary-800' %>
    </div>
  </div>
<% end %>

app/views/main/users/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="mb-4 text-3xl font-extrabold text-gray-900 dark:text-white md:text-5xl lg:text-6xl text-center">
    <span class="text-transparent bg-clip-text bg-gradient-to-r to-emerald-600 from-sky-400">
      Edit User
    </span>  
  </h1>
  <div class="flex justify-center px-4 mx-auto max-w-screen-xl mb-10">
    <%= render 'form', user: @user %>
  </div>
</div>

app/views/main/users/show.html.erb
<div class="flex justify-center px-4 mx-auto max-w-screen-xl mb-10 mt-2">
  <div class="max-w-sm bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700 text-center">
    <div class="py-4 px-10 mx-auto">
      <%= @user.avatar.present? ? image_tag(@user.avatar.variant(:thumb)) : image_tag('https://via.placeholder.com/50') %>
    </div>
    <div class="py-4 px-4 mx-auto">
      <h2 class="mb-2 text-xl font-semibold leading-none text-gray-900 md:text-2xl dark:text-white"><%= @user.display_name %></h2>
      <p class="mb-4 text-xl font-extrabold leading-none text-gray-900 md:text-2xl dark:text-white">@<%= @user.nickname %></p>
      <dl>
        <dt class="mb-2 font-semibold leading-none text-gray-900 dark:text-white">Email:</dt>
        <dd class="mb-4 font-light text-gray-500 sm:mb-5 dark:text-gray-400"><%= @user.email %></dd>
      </dl>
      <dl>
        <div>
          <dt class="mb-2 font-semibold leading-none text-gray-900 dark:text-white">Phone:</dt>
          <dd class="mb-4 font-light text-gray-500 sm:mb-5 dark:text-gray-400"><%= @user.phone_number %></dd>
        </div>
      </dl>
      <div>
        <% if @user == current_user %>
          <%= link_to edit_main_user_path(@user), class: 'text-white inline-flex items-center bg-primary-700 hover:bg-primary-800 focus:ring-4 focus:outline-none focus:ring-primary-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-primary-600 dark:hover:bg-primary-700 dark:focus:ring-primary-800 mb-2' do %>
            <svg aria-hidden="true" class="mr-1 -ml-1 w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M17.414 2.586a2 2 0 00-2.828 0L7 10.172V13h2.828l7.586-7.586a2 2 0 000-2.828z"></path><path fill-rule="evenodd" d="M2 6a2 2 0 012-2h4a1 1 0 010 2H4v10h10v-4a1 1 0 112 0v4a2 2 0 01-2 2H4a2 2 0 01-2-2V6z" clip-rule="evenodd"></path></svg>
            Edit
          <% end %>
          <%= button_to main_user_path(@user), method: :delete, data: {turbo_method: :delete, turbo_confirm: 'You are deleting your account permanently. Are you sure?'}, class: 'inline-flex items-center text-white bg-red-600 hover:bg-red-700 focus:ring-4 focus:outline-none focus:ring-red-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-red-500 dark:hover:bg-red-600 dark:focus:ring-red-900' do %>
            <svg aria-hidden="true" class="w-5 h-5 mr-1.5 -ml-1" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 0 102 0V8a1 1 0 00-1-1z" clip-rule="evenodd"></path></svg>
            Delete
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<% @post.each do |post| %>
  <div class="justify-start px-4 mx-auto max-w-screen-xl mb-10 flex flex-col items-center bg-white border border-gray-200 rounded-lg shadow md:flex-row md:max-w-xl hover:bg-gray-100 dark:border-gray-700 dark:bg-gray-800 dark:hover:bg-gray-700">
    <div class="flex-shrink-0 mr-4">
        <% if post.images.present? %>
          <% post.images.each do |image| %>
            <%= image_tag image, class: 'object-cover w-full rounded-t-lg h-98 md:h-auto md:w-48 md:rounded-none md:rounded-s-lg' %>
          <% end %>
        <% end %>
      </div>
      <div class="flex flex-col justify-between p-4 leading-normal">
        <h5 class="text-2xl font-bold tracking-tight text-gray-900 dark:text-white"><%= post.user&.display_name %></h5>
        <p class="mb-3 font-normal text-gray-700 dark:text-gray-400">@<%= post.user.nickname %></p>
        <p class="mb-3 font-normal text-gray-700 dark:text-gray-400"><%= post.note %></p>
      </div>
    </div>
  </div>
<% end %>